[package]
name = "desttinghim/wired"
version = "0.2.0"
description = "A puzzle platformer game with wire physics."
readme = "README.md"
repository = "https://github.com/desttinghim/wired"

[[module]]
name = "wired"
source = "zig-out/lib/cart.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "game"
